Mayhem
mayhemheroes/spchcat pull request #1
Opened 2022-07-02 13:13 UTC by ennamarie19

2022-07-30 05:06 UTC, xansec requested changes
You have uploaded quite a large corpus which I don't believe is necessary. Usually 1-2 seeds will suffice. Please make the requested changes.

2022-07-30 05:06 UTC, xansec commented on Dockerfile
> +#Build Stage
Please don't use git clone or `ldd`. You don't need to set the AFL env vars at the end here.

2022-07-30 05:06 UTC, xansec commented on Makefile
> -CC := gcc
Rather than removing sections of the Makefile, can you change this so that the CC and TEST-CCFLAGS are optionally included for your fuzz target?

2022-07-30 05:06 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/ennamarie19/spchcat-fuzz:latest
Please omit image name.

2022-07-30 05:06 UTC, xansec commented on scripts/coqui_releases.csv
>  tt_RU,tatar/itml/v0.1.0
Maybe a formatting issue? It doesn't look like you actually changed this file.

2022-07-30 05:06 UTC, xansec commented on scripts/download_models.py
> -#!/usr/bin/env python
Yeah, I think this is a formatting issue. You can/should probably restore upstream's copies.

2022-08-04 02:19 UTC, ennamarie19 commented
@xansec Done! I added one more file (3)  to the corpus just because of the low tests run per second thanks to the machine learning processing done for each run. It really needs the help to get good edge coverage.

2022-08-04 02:21 UTC, xansec commented
Thanks, LGTM!

2022-08-04 02:21 UTC, merged